/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shares;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author MUTHAKA
 */
public class Account extends javax.swing.JFrame {
String high, low, current;
String  currentquery;
Double amount,noshares,calc;

String share, type, month;
           
private Connection con;
private Statement st;
private PreparedStatement stt;
private ResultSet cr;
    /**
     * Creates new form Account
     */
    public Account() {
        initComponents();
        String d = (new Date()).toString(); 
        txtdate.setText(d);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        txtnoshare = new javax.swing.JTextField();
        txtcurrentrate = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btncalcshare = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        combomonth = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        comboshare = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BUY SHARES ");
        setResizable(false);

        jLabel1.setText("NAME");

        jLabel2.setText("NO OF SHARES");

        jLabel3.setText("AMOUNT");

        jLabel4.setText("CURRENT RATE");

        jLabel5.setText("SHARE");

        txtnoshare.setEditable(false);

        txtcurrentrate.setEditable(false);

        btnsave.setText("SAVE ");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btncalcshare.setText("Calc No Shares");
        btncalcshare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcshareActionPerformed(evt);
            }
        });

        jLabel6.setText("MONTH");

        combomonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "june2014", "july2014", "august2014", "september2014", "october2014", "november2014", "december2014", "january2015", "february2015", "march2015", "april2015", "may2015", "june2015", "july2015", "august2015", "september2015", "november2015", "december2015" }));

        jLabel7.setText("DATE");

        txtdate.setEditable(false);

        comboshare.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CIC_Insurance", "Eveready_EA", "Express", "Home_Afrika_Ltd", "Kengen", "Kenolkobil", "Kenya_Airways", "Kenya_Orchads", "Marshalls_EA", "Mumias_Sugar", "Olympia_Capital", "Safaricom_Limited", "Sameer_Africa" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(btncalcshare)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsave)
                    .addComponent(txtname)
                    .addComponent(txtamount)
                    .addComponent(txtnoshare)
                    .addComponent(txtcurrentrate)
                    .addComponent(combomonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtdate)
                    .addComponent(comboshare, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combomonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboshare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnoshare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcurrentrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsave)
                    .addComponent(btncalcshare))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcshareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcshareActionPerformed
        // TODO add your handling code here:
        String amt = txtamount.getText();
        if (amt.length()!=0)
        {
        try
        {
            /* connecting to the database */
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shares","root","root");
           st = con.createStatement();
           share = comboshare.getSelectedItem().toString();
           
           month = combomonth.getSelectedItem().toString();
           
            if (month.equals("june2014"))
           {
               currentquery = "SELECT * FROM june2014";
           }
           if (month.equals("july2014"))
           {
               currentquery = "SELECT * FROM july2014";
           }
           if (month.equals("august2014"))
           {
               currentquery = "SELECT * FROM august2014";
           }
           if (month.equals("september2014"))
           {
               currentquery = "SELECT * FROM september2014";
           }
           if (month.equals("october2014"))
           {
               currentquery = "SELECT * FROM october2014";
           }
           if (month.equals("november2014"))
           {
               currentquery = "SELECT * FROM november2014";
           }
           if (month.equals("december2014"))
           {
               currentquery = "SELECT * FROM december2014";
           }
           if (month.equals("january2015"))
           {
               currentquery = "SELECT * FROM january2015";
           }
           if (month.equals("february2015"))
           {
               currentquery = "SELECT * FROM february2015";
           }
           if (month.equals("march2015"))
           {
               currentquery = "SELECT * FROM march2015";
           }
           if (month.equals("april2015"))
           {
               currentquery = "SELECT * FROM april2015";
           }
           if (month.equals("may2015"))
           {
               currentquery = "SELECT * FROM may2015";
           }
           if (month.equals("june2015"))
           {
               currentquery = "SELECT * FROM june2015";
           }
           if (month.equals("july2015"))
           {
               currentquery = "SELECT * FROM july2015";
           }
           
           cr = st.executeQuery(currentquery);
           
           
            /*while loop that ends by selecting the last value */
             while(cr.next())
        {  
            current = cr.getString(share);
           
        }
             Double p = Double.parseDouble(current);
             System.out.println(current);
             //String amt = txtamount.getText();
             amount = Double.parseDouble(amt);
             calc = (amount/p);
             String c = calc.toString();
             txtnoshare.setText(c);
             
             txtcurrentrate.setText(current);
            
            
        }
        catch(ClassNotFoundException | SQLException ex)
        {
            System.out.println("Error"+ex);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Enter the Amount");
        }
        
    }//GEN-LAST:event_btncalcshareActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        String name,date,amountt,sharee,curr;
        amountt = txtamount.getText();
        name = txtname.getText();
        if ((amountt.length() !=0)&&(name.length() !=0))
        {
        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shares","root","root");
           share = comboshare.getSelectedItem().toString();
           month = combomonth.getSelectedItem().toString();
           //String name,date,amountt,sharee,curr;
           //name = txtname.getText();
           date = txtdate.getText();
           //amountt = txtamount.getText();
           sharee = txtnoshare.getText();
           double s = Double.parseDouble(sharee);
           double kam = Math.round((s*100)/100);
           String shr = String.valueOf(kam);
           curr = txtcurrentrate.getText();
           currentquery = "INSERT INTO account(NAME,MONTH,DATE,SHARE,AMOUNT,NOSHARES,RATE) VALUES(?,?,?,?,?,?,?)";
           
           stt = con.prepareStatement(currentquery);
           stt.setString(1, name);
           stt.setString(2, month);
           stt.setString(3, date);
           stt.setString(4, share);
           stt.setString(5, amountt);
           stt.setString(6, shr);
           stt.setString(7, curr);
           stt.executeUpdate();
           JOptionPane.showMessageDialog(null,"Data Saved Successfully");
        }
        
        catch (ClassNotFoundException | SQLException | NumberFormatException | HeadlessException ex)
        {
            System.out.println(ex);
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please Fill in Your Name and the Amount");
        }
        
    }//GEN-LAST:event_btnsaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Account a = new Account();
                a.setLocationRelativeTo(null);
                a.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcshare;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox combomonth;
    private javax.swing.JComboBox comboshare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtcurrentrate;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnoshare;
    // End of variables declaration//GEN-END:variables
}
