/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shares;
import javax.swing.filechooser.*;
/**
 *
 * @author MUTHAKA
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menufile = new javax.swing.JMenu();
        menufileopen = new javax.swing.JMenuItem();
        menufileaccount = new javax.swing.JMenuItem();
        menufileinsert = new javax.swing.JMenuItem();
        menufileexit = new javax.swing.JMenuItem();
        menuedit = new javax.swing.JMenu();
        menueditaccount = new javax.swing.JMenuItem();
        menuview = new javax.swing.JMenu();
        menuviewaccount = new javax.swing.JMenuItem();
        menuviewgraph = new javax.swing.JMenuItem();
        menuviewrate = new javax.swing.JMenuItem();
        menuviewmonth = new javax.swing.JMenuItem();
        menuhelp = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        menufile.setText("File");

        menufileopen.setText("Open");
        menufileopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menufileopenActionPerformed(evt);
            }
        });
        menufile.add(menufileopen);

        menufileaccount.setText("Open Share Account");
        menufileaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menufileaccountActionPerformed(evt);
            }
        });
        menufile.add(menufileaccount);

        menufileinsert.setText("Insert Shares to DB");
        menufileinsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menufileinsertActionPerformed(evt);
            }
        });
        menufile.add(menufileinsert);

        menufileexit.setText("Exit");
        menufileexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menufileexitActionPerformed(evt);
            }
        });
        menufile.add(menufileexit);

        jMenuBar1.add(menufile);

        menuedit.setText("Edit");
        menuedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menueditActionPerformed(evt);
            }
        });

        menueditaccount.setText("Account");
        menuedit.add(menueditaccount);

        jMenuBar1.add(menuedit);

        menuview.setText("View");
        menuview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewActionPerformed(evt);
            }
        });

        menuviewaccount.setText("Account Status");
        menuviewaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewaccountActionPerformed(evt);
            }
        });
        menuview.add(menuviewaccount);

        menuviewgraph.setText("Graphs");
        menuviewgraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewgraphActionPerformed(evt);
            }
        });
        menuview.add(menuviewgraph);

        menuviewrate.setText("Rate");
        menuviewrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewrateActionPerformed(evt);
            }
        });
        menuview.add(menuviewrate);

        menuviewmonth.setText("Shares in Month");
        menuviewmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuviewmonthActionPerformed(evt);
            }
        });
        menuview.add(menuviewmonth);

        jMenuBar1.add(menuview);

        menuhelp.setText("Help");
        jMenuBar1.add(menuhelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(579, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menufileaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menufileaccountActionPerformed
        // TODO add your handling code here:
        Account a = new Account();
        a.setLocationRelativeTo(null);
        a.setVisible(true);
        a.setDefaultCloseOperation(Account.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menufileaccountActionPerformed

    private void menufileinsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menufileinsertActionPerformed
        // TODO add your handling code here:
        Insertiondb in = new Insertiondb();
        in.setLocationRelativeTo(null);
        in.setVisible(true);
        in.setDefaultCloseOperation(Insertiondb.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menufileinsertActionPerformed

    private void menufileexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menufileexitActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
        
    }//GEN-LAST:event_menufileexitActionPerformed

    private void menueditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menueditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menueditActionPerformed

    private void menuviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuviewActionPerformed

    private void menuviewgraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewgraphActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuviewgraphActionPerformed

    private void menuviewrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewrateActionPerformed
        // TODO add your handling code here:
        Rate r = new Rate();
        r.setLocationRelativeTo(null);
        r.setVisible(true);
        r.setDefaultCloseOperation(Rate.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuviewrateActionPerformed

    private void menuviewmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewmonthActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuviewmonthActionPerformed

    private void menuviewaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuviewaccountActionPerformed
        // TODO add your handling code here:
        ViewAccount va = new ViewAccount();
        va.setLocationRelativeTo(null);
        va.setVisible(true);
        va.setDefaultCloseOperation(ViewAccount.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuviewaccountActionPerformed

    private void menufileopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menufileopenActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menufileopenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Main m = new Main();
                m.setExtendedState(Main.MAXIMIZED_BOTH);
                m.setDefaultCloseOperation(Main.EXIT_ON_CLOSE);
                m.setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu menuedit;
    private javax.swing.JMenuItem menueditaccount;
    private javax.swing.JMenu menufile;
    private javax.swing.JMenuItem menufileaccount;
    private javax.swing.JMenuItem menufileexit;
    private javax.swing.JMenuItem menufileinsert;
    private javax.swing.JMenuItem menufileopen;
    private javax.swing.JMenu menuhelp;
    private javax.swing.JMenu menuview;
    private javax.swing.JMenuItem menuviewaccount;
    private javax.swing.JMenuItem menuviewgraph;
    private javax.swing.JMenuItem menuviewmonth;
    private javax.swing.JMenuItem menuviewrate;
    // End of variables declaration//GEN-END:variables
}
