/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shares;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


/**
 *
 * @author MUTHAKA
 */
public class Rate extends javax.swing.JFrame {
String high, low, current;
String maxquery, minquery, currentquery;
String mx, mn;
String share, type, month;
           String cic = ("CIC_Insurance");
           String ev = ("Eveready_EA");
           String ex = ("Express");
           String hm = ("Home_Afrika_Ltd");
           String kg = ("Kengen");
           String kk = ("Kenolkobil");
           String ka = ("Kenya_Airways");
           String ko = ("Kenya_Orchads");
           String ma = ("Marshalls_EA");
           String ms = ("Mumias_Sugar");
           String oc = ("Olympia_Capital");
           String sf = ("Safaricom_Limited");
           String sa = ("Sameer_Africa");
private Connection con;
private Statement st;
private ResultSet cr;
    /**
     * Creates new form Rate
     */
    public Rate() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txthigh = new javax.swing.JTextField();
        txtlow = new javax.swing.JTextField();
        txtcurrent = new javax.swing.JTextField();
        comboshare = new javax.swing.JComboBox();
        btnfind = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        combomonth = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("SHARE TYPE");

        jLabel2.setText("HIGHEST VALUE");

        jLabel3.setText("LOWEST VALUE");

        jLabel4.setText("CURRENT VALUE");

        txthigh.setEditable(false);

        txtlow.setEditable(false);

        txtcurrent.setEditable(false);

        comboshare.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CIC_Insurance", "Eveready_EA", "Express", "Home_Afrika_Ltd", "Kengen", "Kenolkobil", "Kenya_Airways", "Kenya_Orchads", "Marshalls_EA", "Mumias_Sugar", "Olympia_Capital", "Safaricom_Limited", "Sameer_Africa" }));

        btnfind.setText("FIND");
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });

        jLabel5.setText("MONTH");

        combomonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "june2014", "july2014", "august2014", "september2014", "october2014", "november2014", "december2014", "january2015", "february2015", "march2015", "april2015", "may2015", "june2015", "july2015", "august2015", "september2015", "november2015", "december2015" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnfind)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txthigh, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtlow)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboshare, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(combomonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtcurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combomonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboshare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txthigh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcurrent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnfind)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
       
       try
        {
            /* connecting to the database */
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shares","root","root");
           st = con.createStatement();
           share = comboshare.getSelectedItem().toString();
           
           month = combomonth.getSelectedItem().toString();
           
            if (month.equals("june2014"))
           {
               currentquery = "SELECT * FROM june2014";
           }
           if (month.equals("july2014"))
           {
               currentquery = "SELECT * FROM july2014";
           }
           if (month.equals("august2014"))
           {
               currentquery = "SELECT * FROM august2014";
           }
           if (month.equals("september2014"))
           {
               currentquery = "SELECT * FROM september2014";
           }
           if (month.equals("october2014"))
           {
               currentquery = "SELECT * FROM october2014";
           }
           if (month.equals("november2014"))
           {
               currentquery = "SELECT * FROM november2014";
           }
           if (month.equals("december2014"))
           {
               currentquery = "SELECT * FROM december2014";
           }
           if (month.equals("january2015"))
           {
               currentquery = "SELECT * FROM january2015";
           }
           if (month.equals("february2015"))
           {
               currentquery = "SELECT * FROM february2015";
           }
           if (month.equals("march2015"))
           {
               currentquery = "SELECT * FROM march2015";
           }
           if (month.equals("april2015"))
           {
               currentquery = "SELECT * FROM april2015";
           }
           if (month.equals("may2015"))
           {
               currentquery = "SELECT * FROM may2015";
           }
           if (month.equals("june2015"))
           {
               currentquery = "SELECT * FROM june2015";
           }
           if (month.equals("july2015"))
           {
               currentquery = "SELECT * FROM july2015";
           }
           
           cr = st.executeQuery(currentquery);
           
            Double minimum = 0.0; 
            Double sum = 0.0;
            Double maximum = 0.0;
           
           
            
            /*while loop that ends by selecting the last value */
             while(cr.next())
        {  
            current = cr.getString(share);
            Double p = Double.parseDouble(current);
            
            sum=sum+p;
            if (p > maximum)
            {
               maximum=p; 
            }
            if (p < minimum)
            {
               minimum=p; 
            }
        }
             Double p = Double.parseDouble(current);
             System.out.println(current);
             txtcurrent.setText(current);
             mx = maximum.toString();
             mn = minimum.toString();
             txthigh.setText(mx);
             txtlow.setText(mn);
             
             
             
        }
        catch(ClassNotFoundException | SQLException ex)
        {
            System.out.println("Error"+ex);
        }
        
        
    }//GEN-LAST:event_btnfindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Rate r = new Rate();
                r.setLocationRelativeTo(null);
                r.setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfind;
    private javax.swing.JComboBox combomonth;
    private javax.swing.JComboBox comboshare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcurrent;
    private javax.swing.JTextField txthigh;
    private javax.swing.JTextField txtlow;
    // End of variables declaration//GEN-END:variables
}
