/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shares;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author MUTHAKA
 */
public class TableData extends javax.swing.JFrame {
private Connection con;
private Statement st;
private ResultSet cr;
String currentquery, current;
String share, month;
    /**
     * Creates new form TableData
     */
    public TableData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        combomonth = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        comboshare = new javax.swing.JComboBox();
        btnshowtbl = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("SELECT MONTH");

        combomonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "june2014", "july2014", "august2014", "september2014", "october2014", "november2014", "december2014", "january2015", "february2015", "march2015", "april2015", "may2015", "june2015", "july2015", "august2015", "september2015", "november2015", "december2015" }));

        jLabel2.setText("TYPE OF SHARE");

        comboshare.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "CIC_Insurance", "Eveready_EA", "Express", "Home_Afrika_Ltd", "Kengen", "Kenolkobil", "Kenya_Airways", "Kenya_Orchads", "Marshalls_EA", "Mumias_Sugar", "Olympia_Capital", "Safaricom_Limited", "Sameer_Africa" }));

        btnshowtbl.setText("SHOW TABLE");
        btnshowtbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowtblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnshowtbl)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboshare, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(combomonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(combomonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboshare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnshowtbl)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowtblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowtblActionPerformed
        // TODO add your handling code here:
        try
        {
            /* connecting to the database */
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shares","root","root");
           st = con.createStatement();
           share = comboshare.getSelectedItem().toString();
           month = combomonth.getSelectedItem().toString();
           
           if (month.equals("june2014"))
           {
               currentquery = "SELECT * FROM june2014";
           }
           if (month.equals("july2014"))
           {
               currentquery = "SELECT * FROM july2014";
           }
           if (month.equals("august2014"))
           {
               currentquery = "SELECT * FROM august2014";
           }
           if (month.equals("september2014"))
           {
               currentquery = "SELECT * FROM september2014";
           }
           if (month.equals("october2014"))
           {
               currentquery = "SELECT * FROM october2014";
           }
           if (month.equals("november2014"))
           {
               currentquery = "SELECT * FROM november2014";
           }
           if (month.equals("december2014"))
           {
               currentquery = "SELECT * FROM december2014";
           }
           if (month.equals("january2015"))
           {
               currentquery = "SELECT * FROM january2015";
           }
           if (month.equals("february2015"))
           {
               currentquery = "SELECT * FROM february2015";
           }
           if (month.equals("march2015"))
           {
               currentquery = "SELECT * FROM march2015";
           }
           if (month.equals("april2015"))
           {
               currentquery = "SELECT * FROM april2015";
           }
           if (month.equals("may2015"))
           {
               currentquery = "SELECT * FROM may2015";
           }
           if (month.equals("june2015"))
           {
               currentquery = "SELECT * FROM june2015";
           }
           if (month.equals("july2015"))
           {
               currentquery = "SELECT * FROM july2015";
           }
           
           cr = st.executeQuery(currentquery);
           
        if (share.equals("ALL"))
        {
            System.out.println("welcome");
        }
        else  
                {
            /*while loop that ends by selecting the last value */
                    while(cr.next())
                   {  
                     current = cr.getString(share);
                     Double p = Double.parseDouble(current);
            
            
                   }
             
                   System.out.println(current);
                   
                }
             
        }
        catch(ClassNotFoundException | SQLException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnshowtblActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TableData td = new TableData();
                td.setLocationRelativeTo(null);
                td.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnshowtbl;
    private javax.swing.JComboBox combomonth;
    private javax.swing.JComboBox comboshare;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
