/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shares;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;



/**
 *
 * @author MUTHAKA
 */
public class ViewAccount extends javax.swing.JFrame {
String sh,dt,amt,nosh,rt,mth;
String query, current,q,ids;
private Connection con;
private Statement st;
PreparedStatement pst;
private ResultSet cr;
ResultSet crt;
Double A,P,L,N,S;
String ss,aa;
String loss,profit;
String a,n,prev;
String nme;


    /**
     * Creates new form ViewAccount
     */
    public ViewAccount() {
        initComponents();
         try
         {
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shares","root","root");
           st = con.createStatement();
           q = "SELECT * FROM account";
          
           crt = st.executeQuery(q);

            while (crt.next()) {
                ids = crt.getString("NAME");
                comboname.addItem(ids);
            }
           
            st.close();
            crt.close();
         }
         catch (ClassNotFoundException | SQLException ex)
         {
             System.out.println(ex);
         }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnload = new javax.swing.JButton();
        comboname = new javax.swing.JComboBox();
        txtshare = new javax.swing.JTextField();
        txtloss = new javax.swing.JTextField();
        txtcurrentrate = new javax.swing.JTextField();
        txtprofit = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        txtmonth = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtprevrate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btncalculate = new javax.swing.JButton();
        combomonth = new javax.swing.JComboBox();
        cmdclear = new javax.swing.JButton();
        txtnoshares = new javax.swing.JTextField();
        txtamount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttodaydate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtnodays = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULATE PROFIT AND LOSS");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jLabel1.setText("NAME");

        jLabel2.setText("COMPANY");

        jLabel3.setText("AMOUNT");

        jLabel4.setText("NO OF SHARES");

        jLabel5.setText("CURRENT RATE ");

        jLabel6.setText("PROFIT");

        btnload.setText("LOAD");
        btnload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloadActionPerformed(evt);
            }
        });

        txtshare.setEditable(false);

        txtloss.setEditable(false);

        txtcurrentrate.setEditable(false);

        txtprofit.setEditable(false);

        jLabel8.setText(" MONTH BOUGHT");

        jLabel9.setText("DATE");

        txtdate.setEditable(false);

        txtmonth.setEditable(false);

        jLabel10.setText("RATE PER SHARE");

        txtprevrate.setEditable(false);

        jLabel11.setText("CURRENT MONTH");

        jLabel12.setText("LOSS");

        btncalculate.setText("CALCULATE");
        btncalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalculateActionPerformed(evt);
            }
        });

        combomonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "june2014", "july2014", "august2014", "september2014", "october2014", "november2014", "december2014", "january2015", "february2015", "march2015", "april2015", "may2015", "june2015", "july2015", "august2015", "september2015", "november2015", "december2015" }));

        cmdclear.setText("CLEAR TEXT");
        cmdclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdclearActionPerformed(evt);
            }
        });

        txtnoshares.setEditable(false);

        txtamount.setEditable(false);

        jLabel7.setText("TODAYS DATE");

        txttodaydate.setEditable(false);

        jLabel13.setText("DAYS");

        txtnodays.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtprevrate)
                            .addComponent(txtamount)
                            .addComponent(txtshare, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtmonth, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboname, 0, 180, Short.MAX_VALUE)
                            .addComponent(txtnoshares)
                            .addComponent(txtdate))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnload, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btncalculate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdclear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcurrentrate)
                            .addComponent(combomonth, 0, 182, Short.MAX_VALUE)
                            .addComponent(txtprofit)
                            .addComponent(txtloss)
                            .addComponent(txttodaydate)
                            .addComponent(txtnodays))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(combomonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcurrentrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtprofit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(txtdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtshare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12)
                    .addComponent(txtloss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtamount))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txttodaydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtnoshares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtnodays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtprevrate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnload)
                    .addComponent(btncalculate)
                    .addComponent(cmdclear))
                .addGap(63, 91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloadActionPerformed
        // TODO add your handling code here:
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shares","root","root");
           st = con.createStatement();
           nme = comboname.getSelectedItem().toString();
           query = ("SELECT * FROM account WHERE NAME='"+nme+"' ");
          
           cr = st.executeQuery(query);
            while(cr.next())
             {  
            mth = cr.getString("MONTH");
            dt = cr.getString("DATE");
            sh = cr.getString("SHARE");
            amt = cr.getString("AMOUNT");
            nosh = cr.getString("NOSHARES");
            rt = cr.getString("RATE");
            
            }
            txtmonth.setText(mth);
            txtdate.setText(dt);
            txtshare.setText(sh);
            txtamount.setText(amt);
            txtnoshares.setText(nosh);
            txtprevrate.setText(rt);
            
        }
        catch (ClassNotFoundException | SQLException ex)
        {
            System.out.println(ex);
        }
        P = 0.0;
        S = 0.0;
    }//GEN-LAST:event_btnloadActionPerformed

    private void btncalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalculateActionPerformed
        // TODO add your handling code here:
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
           con = DriverManager.getConnection("jdbc:mysql://localhost:3306/shares","root","root");
           st = con.createStatement();
          String month = combomonth.getSelectedItem().toString();
          String shar = txtshare.getText();
           
            if (month.equals("june2014"))
           {
               query = "SELECT * FROM june2014";
           }
           if (month.equals("july2014"))
           {
               query = "SELECT * FROM july2014";
           }
           if (month.equals("august2014"))
           {
               query = "SELECT * FROM august2014";
           }
           if (month.equals("september2014"))
           {
               query = "SELECT * FROM september2014";
           }
           if (month.equals("october2014"))
           {
               query = "SELECT * FROM october2014";
           }
           if (month.equals("november2014"))
           {
               query = "SELECT * FROM november2014";
           }
           if (month.equals("december2014"))
           {
               query = "SELECT * FROM december2014";
           }
           if (month.equals("january2015"))
           {
               query = "SELECT * FROM january2015";
           }
           if (month.equals("february2015"))
           {
               query = "SELECT * FROM february2015";
           }
           if (month.equals("march2015"))
           {
               query = "SELECT * FROM march2015";
           }
           if (month.equals("april2015"))
           {
               query = "SELECT * FROM april2015";
           }
           if (month.equals("may2015"))
           {
               query = "SELECT * FROM may2015";
           }
           if (month.equals("june2015"))
           {
               query = "SELECT * FROM june2015";
           }
           if (month.equals("july2015"))
           {
               query = "SELECT * FROM july2015";
           }
           
           
           cr = st.executeQuery(query);
            while(cr.next())
             {  
            current = cr.getString(shar);
            
            }
            Double ct = Double.parseDouble(current);
            txtcurrentrate.setText(current);
            
            String d = (new Date()).toString(); 
            txttodaydate.setText(d);
             
            a = txtamount.getText();
            A = Double.parseDouble(a);
            n = txtnoshares.getText();
            N = Double.parseDouble(n);
            prev = txtprevrate.getText();
            
            
            S = (N*ct);
            aa = A.toString();
            ss = S.toString();
            
            
            if (S>A)
            { 
               P = (S-A);
               double kam = Math.round(P*100)/100;
               profit = String.valueOf(kam);
               txtprofit.setText(profit);
               txtloss.setText("0.00");
            }
            if (A>S)
            {  
               L = (A-S);
               double kam = Math.round(L*100)/100;
               loss = String.valueOf(kam);
               txtloss.setText(loss);
               txtprofit.setText("0.00");
               
               
            }
            if (aa.equals(ss))
            {  
               txtprofit.setText("0.00");
               txtloss.setText("0.00");
            }
            
        }
        catch (ClassNotFoundException | SQLException | NumberFormatException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btncalculateActionPerformed

    private void cmdclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdclearActionPerformed
        // TODO add your handling code here:
        txtcurrentrate.setText("");
        txtprofit.setText("");
        txtloss.setText("");
        txttodaydate.setText("");
        P = 0.00;
        S = 0.00;
    }//GEN-LAST:event_cmdclearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewAccount va = new ViewAccount();
                va.setLocationRelativeTo(null);
                va.setVisible(true);
                
               
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalculate;
    private javax.swing.JButton btnload;
    private javax.swing.JButton cmdclear;
    private javax.swing.JComboBox combomonth;
    private javax.swing.JComboBox comboname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtcurrentrate;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtloss;
    private javax.swing.JTextField txtmonth;
    private javax.swing.JTextField txtnodays;
    private javax.swing.JTextField txtnoshares;
    private javax.swing.JTextField txtprevrate;
    private javax.swing.JTextField txtprofit;
    private javax.swing.JTextField txtshare;
    private javax.swing.JTextField txttodaydate;
    // End of variables declaration//GEN-END:variables
}
